# Generated by Django 4.0.4 on 2022-10-14 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(max_length=8)),
                ('seq_no', models.IntegerField()),
                ('instruction', models.CharField(max_length=200)),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.recipe')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recipeinstruction',
            constraint=models.UniqueConstraint(fields=('r_id', 'seq_no'), name='r_seq'),
        ),
    ]
