# Generated by Django 4.0.4 on 2022-10-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_recipe_author_recipe_date_posted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
